version: 2
updates:
  # Node.js backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "team-devops"
    assignees:
      - "team-devops"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "team-devops"
    assignees:
      - "team-devops"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Flutter dependencies
  - package-ecosystem: "pub"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
            day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "team-devops"
    assignees:
      - "team-devops"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Flutter dependencies
  - package-ecosystem: "pub"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "team-devops"
    assignees:
      - "team-devops"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "team-devops"
    assignees:
      - "team-devops"
    commit-message:
      prefix: "ci"
      include: "scope"
