name: hadhir_business
description: Order receiver app UI - Pure Flutter UI Demo

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  intl: ^0.20.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_riverpod: ^2.4.9
  provider: ^6.1.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.1.2
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_api: ^2.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.5
  firebase_messaging: ^15.1.4
  web_socket_channel: ^2.4.0
  audioplayers: ^5.2.1
  flutter_local_notifications: ^17.2.3
  http_parser: ^4.0.2
  uuid: ^4.4.2
  geolocator: ^10.1.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/sounds/
