name: hadhir_business
description: Order receiver app for stores and restaurants

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^10.2.0
  google_fonts: ^6.1.0
  flutter_local_notifications: ^17.0.0
  audioplayers: ^6.5.0
  permission_handler: ^11.2.0
  fl_chart: ^0.66.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  http: ^1.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2
  get_it: ^7.6.7
  web_socket_channel: ^2.4.0
  # AWS Amplify for Cognito authentication
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_api: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/sounds/
