version = 0.1

[default.deploy.parameters]
stack_name = "order-receiver-regional-dev"
resolve_s3 = true
s3_prefix = "order-receiver-regional-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" CognitoUserPoolId=\"us-east-1_PHPkG78b5\" CognitoClientId=\"1tl9g7nk2k2chtj5fg960fgdth\" CacheVersion=\"v2\""
image_repositories = []
