version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hadhir-business-api"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=production",
  "SecretKey=9bbf7c3a0ad65491ff260b29f8d4b2df22814e50c776ef505e8c3edca5b07b8e",
  "CorsOrigins=*",
  "DynamoDBTableName=order-receiver-data-v2"
]
confirm_changeset = true
disable_rollback = false
s3_prefix = "hadhir-business-api"
image_repositories = []

[default.build]
[default.build.parameters]
parallel = true
